import { COLORS } from "@/constants/DiabetesConstants";
import { Platform, StyleSheet } from "react-native";

export default StyleSheet.create({
  /* _layout.txt*/

  fabContainer: {
    position: "absolute",
    bottom: 150, // Position slightly higher with the taller tab bar
    left: "50%", // Start from center
    marginLeft: -28, // Half of width to center the container
    alignItems: "center",
    zIndex: 1000,
  },
  floatingButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    marginBottom: 4, // Space between button and label
  },
  fabLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.primary,
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "80%",
  },
  modalContent: {
    padding: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: COLORS.primary,
    textAlign: "center",
    marginBottom: 20,
  },
  sectionTitleSmall: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.primary,
    marginTop: 15,
    marginBottom: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.primaryLight,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginBottom: 10,
    backgroundColor: "#f9f9f9",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    marginBottom: 10,
  },
  button: {
    flex: 1,
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: "#f0f0f0",
    borderWidth: 1,
    borderColor: COLORS.gray,
  },
  submitButton: {
    backgroundColor: COLORS.primary,
  },
  cancelButtonText: {
    color: COLORS.gray,
    fontSize: 16,
    fontWeight: "bold",
  },
  submitButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },

  /* chat.tsx */
  container: {
    flex: 1,
    backgroundColor: COLORS.primary, // Use app's primary purple
  },
  header: {
    backgroundColor: COLORS.primary,
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerContent: {
    flex: 1,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.white,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.primaryLight,
    alignItems: "center",
    justifyContent: "center",
  },
  chatContainer: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginTop: 10,
    overflow: "hidden",
  },
  chatHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.primaryCircle,
    backgroundColor: COLORS.white,
  },
  chatHeaderText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.dark,
  },
  messagesContainer: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  messageContainer: {
    flexDirection: "row",
    marginBottom: 16,
    alignItems: "flex-start",
  },
  aiMessage: {
    justifyContent: "flex-start",
  },
  userMessage: {
    justifyContent: "flex-end",
  },
  userMessageBubble: {
    maxWidth: "80%",
    backgroundColor: COLORS.primary,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 18,
    borderTopRightRadius: 4,
  },
  userMessageText: {
    fontSize: 15,
    lineHeight: 20,
    color: COLORS.white,
  },
  userMessageTime: {
    fontSize: 11,
    color: "rgba(255,255,255,0.7)",
    marginTop: 4,
  },
  userAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.gray,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  loadingContainer: {
    flexDirection: "row",
    marginBottom: 16,
    alignItems: "flex-start",
  },
  loadingText: {
    fontSize: 14,
    color: COLORS.gray,
    marginLeft: 8,
    fontStyle: "italic",
  },
  aiAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  aiAvatarText: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.white,
  },
  aiMessageBubble: {
    maxWidth: "80%",
    backgroundColor: COLORS.primaryBg,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 18,
    borderTopLeftRadius: 4,
  },
  aiMessageText: {
    fontSize: 15,
    lineHeight: 20,
    color: COLORS.dark,
  },
  messageTime: {
    fontSize: 11,
    color: COLORS.gray,
    marginTop: 4,
  },
  optionsContainer: {
    paddingVertical: 16,
    alignItems: "flex-end",
  },
  optionButton: {
    backgroundColor: COLORS.primary, // Use app's blue color
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 20,
    marginBottom: 8,
    maxWidth: "75%",
  },
  optionText: {
    fontSize: 14,
    color: COLORS.white,
    fontWeight: "500",
    textAlign: "center",
  },
  skipButton: {
    backgroundColor: "transparent",
    paddingHorizontal: 20,
    paddingVertical: 8,
    marginTop: 8,
  },
  skipText: {
    fontSize: 14,
    color: COLORS.gray,
    textAlign: "center",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 16,
    paddingVertical: 16,
    paddingBottom: Platform.OS === "ios" ? 150 : 150, // Account for tab bar height (100px) + padding
    borderTopWidth: 1,
    borderTopColor: COLORS.primaryCircle,
    backgroundColor: COLORS.white,
  },
  textInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.primaryCircle,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginRight: 12,
    maxHeight: 100,
    fontSize: 16,
    color: COLORS.dark,
    backgroundColor: COLORS.white,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  sendButtonDisabled: {
    backgroundColor: COLORS.gray,
    opacity: 0.5,
  },

  /* explore.tsx */

  headerImage: {
    color: "#808080",
    bottom: -90,
    left: -35,
    position: "absolute",
  },
  titleContainer: {
    flexDirection: "row",
    gap: 8,
  },

  /* logs.tsx */

  log_container: {
    flex: 1,
    padding: 20,
    backgroundColor: COLORS.white,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 8,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  log_inputContainer: {
    flex: 1,
  },
  inputLabel: {
    color: COLORS.gray,
    fontSize: 13,
    marginBottom: 2,
  },
  log_input: {
    borderWidth: 1,
    borderColor: COLORS.primaryLight,
    borderRadius: 8,
    padding: 8,
    fontSize: 15,
    backgroundColor: COLORS.grayBg,
    color: COLORS.dark,
  },
  addButton: {
    marginLeft: 8,
    backgroundColor: "transparent",
  },
  logList: {
    marginTop: 4,
    marginBottom: 8,
  },
  logItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grayBg,
  },
  logText: {
    color: COLORS.dark,
    fontSize: 15,
  },
  logTime: {
    color: COLORS.grayLight,
    fontSize: 13,
  },

  /* predictor */
  predictor_container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  predictor_header: {
    padding: 20,
    paddingBottom: 10,
    paddingTop: 60,
    backgroundColor: COLORS.white,
  },
  predictor_headerTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 16,
    color: COLORS.gray,
  },
  chartCard: {
    backgroundColor: COLORS.white,
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  chartHeader: {
    marginBottom: 20,
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 4,
  },
  chartSubtitle: {
    fontSize: 14,
    color: COLORS.gray,
  },
  chartContainer: {
    position: "relative",
    height: 140,
    marginBottom: 15,
  },
  chartBackground: {
    position: "absolute",
    left: 40,
    right: 0,
    top: 0,
    bottom: 20,
    backgroundColor: "#f8fafc",
    borderRadius: 8,
  },
  gridLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "#e5e7eb",
  },
  dataPoint: {
    position: "absolute",
    width: 10,
    height: 10,
    borderRadius: 5,
    marginLeft: -5,
    marginBottom: -5,
  },
  dividerLine: {
    position: "absolute",
    left: "50%",
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: COLORS.primary,
    opacity: 0.3,
  },
  yAxisLabels: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 20,
    width: 35,
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  xAxisLabels: {
    position: "absolute",
    left: 40,
    right: 0,
    bottom: 0,
    height: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  axisLabel: {
    fontSize: 11,
    color: COLORS.gray,
  },
  legend: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 20,
    marginTop: 10,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  legendText: {
    fontSize: 12,
    color: COLORS.gray,
  },
  analysisCard: {
    backgroundColor: COLORS.white,
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  analysisHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  analysisTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.primary,
    marginLeft: 8,
  },
  trendContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  trendLabel: {
    fontSize: 16,
    color: COLORS.gray,
    marginRight: 8,
  },
  trendValue: {
    fontSize: 16,
    fontWeight: "bold",
  },
  adviceText: {
    fontSize: 14,
    color: COLORS.gray,
    lineHeight: 20,
    marginBottom: 15,
  },
  predictionDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  detailItem: {
    alignItems: "center",
  },
  detailLabel: {
    fontSize: 12,
    color: COLORS.gray,
    marginBottom: 4,
  },
  detailValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  insightsCard: {
    backgroundColor: COLORS.white,
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  insightsHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  insightsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.primary,
    marginLeft: 8,
  },
  insightsList: {
    gap: 10,
  },
  insightItem: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  insightText: {
    fontSize: 14,
    color: COLORS.gray,
    lineHeight: 20,
    flex: 1,
  },

  /* profile.tsx */
  contactSection: {
    marginTop: 20,
    padding: 20,
    //backgroundColor: COLORS.grayLight, // Corrected from lightGray to grayLight
    ////borderRadius: 12,
   // shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 15,
    textAlign: "center",
  },
  contactItem: {
    marginBottom: 15,
    padding: 15,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 3,
  },
  contactLabel: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.primary,
    marginBottom: 5,
  },
  contactValue: {
    fontSize: 16,
    color: COLORS.dark,
  },
  contactMerged: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
    padding: 15,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 3,
  },
  cgmSmartWatchContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
    padding: 15,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 3,
  },
  cgmSmartWatchLabel: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.primary,
  },
  cgmSmartWatchValue: {
    fontSize: 16,
    color: COLORS.dark,
  },
  profile_container: {
    flex: 1,
    backgroundColor: COLORS.white,
    paddingTop: 60,
    paddingBottom: 20,
  },
  profile_header: {
    paddingHorizontal: 20,
    paddingBottom: 30,
    alignItems: "center",
  },
  profile_headerTitle: {
    paddingTop: 20,
    fontSize: 28,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  profileCard: {
    backgroundColor: COLORS.white,
    marginHorizontal: 20,

    padding: 30,
    alignItems: "center",
  },
  profileImageContainer: {
    marginBottom: 20,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 4,
    borderColor: COLORS.primaryLight,
  },
  userName: {
    paddingTop: 30,
    fontSize: 24,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 20,
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: "#e5e7eb",
    marginVertical: 20,
  },
  infoSection: {
    width: "100%",
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  infoItem: {
    flex: 1,
    marginHorizontal: 5,
  },
  infoLabel: {
    fontSize: 14,
    color: COLORS.gray,
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.primary,
  },
  menuSection: {
    width: "100%",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary,
  },
  menuText: {
    flex: 1,
    fontSize: 16,
    color: COLORS.primary,
    marginLeft: 15,
    fontWeight: "500",
  },

  /* sensors.tsx */
  sensor_container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  sensor_header: {
    padding: 20,
    paddingBottom: 10,
    paddingTop: 60,
    backgroundColor: COLORS.white,
  },
  sensor_headerTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 4,
  },
  sensor_headerSubtitle: {
    fontSize: 16,
    color: COLORS.gray,
  },
  cgmContainer: {
    alignItems: "center",
    paddingVertical: 30,
    paddingHorizontal: 20,
    backgroundColor: COLORS.white,
  },
  circularMeter: {
    width: 200,
    height: 200,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  backgroundCircle: {
    position: "absolute",
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 8,
    borderColor: "#f3f4f6",
    backgroundColor: "transparent",
  },
  circularProgressBar: {
    position: "absolute",
    width: 12,
    height: 20,
    backgroundColor: "#10b981",
    borderRadius: 6,
    top: "50%",
    left: "50%",
    marginLeft: -6,
    marginTop: -10,
  },
  centerContent: {
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  glucoseValue: {
    fontSize: 48,
    fontWeight: "bold",
    color: COLORS.primary,
    lineHeight: 52,
  },
  glucoseUnit: {
    fontSize: 16,
    color: COLORS.gray,
    marginBottom: 8,
  },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  statusText: {
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 4,
  },
  rangeLabel1: {
    position: "absolute",
    bottom: 0,
    left: 20,
    fontSize: 12,
    color: COLORS.gray,
    fontWeight: "500",
  },
  rangeLabel2: {
    position: "absolute",
    top: 0,
    right: 20,
    fontSize: 12,
    color: COLORS.gray,
    fontWeight: "500",
  },
  lastReading: {
    fontSize: 14,
    color: COLORS.gray,
    textAlign: "center",
  },
  metricsGrid: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  metricsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  metricCard: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  sleepCard: {
    borderLeftWidth: 4,
    borderLeftColor: "#6366f1",
    width: "48%",
  },
  heartRateCard: {
    borderLeftWidth: 4,
    borderLeftColor: "#ef4444",
    width: "48%",
  },
  stepsCard: {
    borderLeftWidth: 4,
    borderLeftColor: "#f59e0b",
    width: "100%",
  },
  metricHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  metricTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.primary,
    marginLeft: 8,
  },
  metricValue: {
    fontSize: 32,
    fontWeight: "bold",
    color: COLORS.primary,
    lineHeight: 36,
  },
  metricSubtext: {
    fontSize: 14,
    color: COLORS.gray,
    marginTop: 4,
  },
  sleepQuality: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
  },
  qualityDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  qualityText: {
    fontSize: 12,
    color: COLORS.gray,
  },
  heartRateRange: {
    marginTop: 8,
  },
  rangeText: {
    fontSize: 12,
    color: COLORS.gray,
  },
  stepsContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  stepsLeft: {
    flex: 1,
  },
  stepsProgress: {
    flex: 1,
    marginLeft: 20,
    alignItems: "flex-end",
  },
  progressBar: {
    width: "100%",
    height: 8,
    backgroundColor: "#f3f4f6",
    borderRadius: 4,
    marginBottom: 6,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#f59e0b",
    borderRadius: 4,
  },
  progressText: {
    fontSize: 12,
    color: COLORS.gray,
  },
  quickStats: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: "#f8fafc",
    marginHorizontal: 20,
    borderRadius: 16,
    marginBottom: 20,
  },
  trendChart: {
    backgroundColor: COLORS.white,
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  sensor_chartHeader: {
    marginBottom: 20,
  },
  sensor_chartTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 4,
  },
  sensor_chartSubtitle: {
    fontSize: 14,
    color: COLORS.gray,
  },
  sensor_chartContainer: {
    position: "relative",
    height: 120,
    marginBottom: 10,
  },
  sensor_chartBackground: {
    position: "absolute",
    left: 40,
    right: 0,
    top: 0,
    bottom: 20,
    backgroundColor: "#f8fafc",
    borderRadius: 8,
  },
  sensor_gridLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "#e5e7eb",
  },
  trendLine: {
    position: "absolute",
    left: 40,
    right: 0,
    top: 0,
    bottom: 20,
  },
  sensor_dataPoint: {
    position: "absolute",
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#10b981",
    marginLeft: -4,
    marginBottom: -4,
  },
});
